on:
  push:
    branches: [ main ]
  schedule:
  - cron: '0 2 * * 1-5'
jobs:
  build:
    name: test shell
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: "pwd && ls -la"
    
